apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: kir97/kubernets:order-service
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 500m
              memory: "512Mi"
            requests:
              cpu: 250m
              memory: "256Mi"
