apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: kir97/kubernets:product-service
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 500m
              memory: "512Mi"
            requests:
              cpu: 250m
              memory: "256Mi"
