name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Build and push Docker images
        run: |
          docker build -t ${{ secrets.DOCKER_USER }}/product-service:latest ./microsservicos/micro-product
          docker build -t ${{ secrets.DOCKER_USER }}/order-service:latest ./microsservicos/micro-order
          docker push ${{ secrets.DOCKER_USER }}/product-service:latest
          docker push ${{ secrets.DOCKER_USER }}/order-service:latest

      - name: Set up Kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'latest'

      - name: Deploy to Kubernetes
        env:
          KUBECONFIG: ${{ secrets.KUBECONF }}
        run: |
          kubectl apply -f kubernetes/product-service-deploy.yml
          kubectl apply -f kubernetes/order-service-deploy.yml
